### ISSUE TITLE
Fix errors in new indexer extension

### ISSUE THREAD

**Issue by pablogiralt** [jimmylion/jimmylion-magento2-vsbridge-indexer-extension#1]
To review with rafael, this is the trace of the error I am getting:

```
/public/vendor/coding-mice/magento2-vsbridge-indexer-extension/Plugin/Catalog/Model/Indexer/DataProvider/Product/ConfigurableDataExtender.php

method afterAddData - Line 44
Method extendDataWithGallery - Line 156
Method getIndex - Line 353

/public/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-core/Index/IndexOperations.php

Method getIndexByName - Line 145 
```

**Comment by pablogiralt** [comment]
this is the branch we should be working on:

2001_new_indexer_version

**Comment by RafaelYD** [comment]
@pablogiralt Commit fixes the issue, and the plugin does not block anymore in the extendDataWithGallery method...

I suspect the reason was in the way how the classes were loaded (via ObjectManager), I removed the objectManager and load them via Dependency Injection. This fixed the mentioned issue

**Comment by pablogiralt** [comment]
@RafaelYD works great. Nice work!
